* **配置选项**

  有没有想过你在 ``config/packages/*.yaml`` 文件中可以使用哪些配置选项？
  在本节中，所有可用配置都由用于定义Symfony配置的每个可能部分的键（例如框架）进行细分。

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`
  * :doc:`debug </reference/configuration/debug>`

* :doc:`配置内核 </reference/configuration/kernel>`

* **表单和验证**

  * :doc:`表单字段类型参考 </reference/forms/types>`
  * :doc:`验证约束参考 </reference/constraints>`
  * :doc:`Twig模板函数和变量参考 </reference/forms/twig_reference>`

* :doc:`Twig扩展(表单、过滤器、标签等等)参考 </reference/twig_reference>`

* **其他**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/events`
  * :doc:`/reference/requirements`
