文本字段
~~~~~~~~~~~

* :doc:`TextType </reference/forms/types/text>`
* :doc:`TextareaType </reference/forms/types/textarea>`
* :doc:`EmailType </reference/forms/types/email>`
* :doc:`IntegerType </reference/forms/types/integer>`
* :doc:`MoneyType </reference/forms/types/money>`
* :doc:`NumberType </reference/forms/types/number>`
* :doc:`PasswordType </reference/forms/types/password>`
* :doc:`PercentType </reference/forms/types/percent>`
* :doc:`SearchType </reference/forms/types/search>`
* :doc:`UrlType </reference/forms/types/url>`
* :doc:`RangeType </reference/forms/types/range>`
* :doc:`TelType </reference/forms/types/tel>`
* :doc:`ColorType </reference/forms/types/color>`

选择型字段
~~~~~~~~~~~~~

* :doc:`ChoiceType </reference/forms/types/choice>`
* :doc:`EntityType </reference/forms/types/entity>`
* :doc:`CountryType </reference/forms/types/country>`
* :doc:`LanguageType </reference/forms/types/language>`
* :doc:`LocaleType </reference/forms/types/locale>`
* :doc:`TimezoneType </reference/forms/types/timezone>`
* :doc:`CurrencyType </reference/forms/types/currency>`

日期和时间字段
~~~~~~~~~~~~~~~~~~~~

* :doc:`DateType </reference/forms/types/date>`
* :doc:`DateIntervalType </reference/forms/types/dateinterval>`
* :doc:`DateTimeType </reference/forms/types/datetime>`
* :doc:`TimeType </reference/forms/types/time>`
* :doc:`BirthdayType </reference/forms/types/birthday>`

其他字段
~~~~~~~~~~~~

* :doc:`CheckboxType </reference/forms/types/checkbox>`
* :doc:`FileType </reference/forms/types/file>`
* :doc:`RadioType </reference/forms/types/radio>`

字段组
~~~~~~~~~~~~

* :doc:`CollectionType </reference/forms/types/collection>`
* :doc:`RepeatedType </reference/forms/types/repeated>`

隐藏字段
~~~~~~~~~~~~~

* :doc:`HiddenType </reference/forms/types/hidden>`

按钮
~~~~~~~

* :doc:`ButtonType </reference/forms/types/button>`
* :doc:`ResetType </reference/forms/types/reset>`
* :doc:`SubmitType </reference/forms/types/submit>`

表单字段基类
~~~~~~~~~~~~~~~~~

* :doc:`FormType </reference/forms/types/form>`
