基本约束
~~~~~~~~~~~~~~~~~

这些是基本约束：使用它们来断言关于属性值或对象上方法的返回值的非常基本的东西。

* :doc:`NotBlank </reference/constraints/NotBlank>`
* :doc:`Blank </reference/constraints/Blank>`
* :doc:`NotNull </reference/constraints/NotNull>`
* :doc:`IsNull </reference/constraints/IsNull>`
* :doc:`IsTrue </reference/constraints/IsTrue>`
* :doc:`IsFalse </reference/constraints/IsFalse>`
* :doc:`Type </reference/constraints/Type>`

字符串约束
~~~~~~~~~~~~~~~~~~

* :doc:`Email </reference/constraints/Email>`
* :doc:`Length </reference/constraints/Length>`
* :doc:`Url </reference/constraints/Url>`
* :doc:`Regex </reference/constraints/Regex>`
* :doc:`Ip </reference/constraints/Ip>`
* :doc:`Uuid</reference/constraints/Uuid>`
* :doc:`UserPassword </reference/constraints/UserPassword>`

比较约束
~~~~~~~~~~~~~~~~~~~~~~

* :doc:`EqualTo </reference/constraints/EqualTo>`
* :doc:`NotEqualTo </reference/constraints/NotEqualTo>`
* :doc:`IdenticalTo </reference/constraints/IdenticalTo>`
* :doc:`NotIdenticalTo </reference/constraints/NotIdenticalTo>`
* :doc:`LessThan </reference/constraints/LessThan>`
* :doc:`LessThanOrEqual </reference/constraints/LessThanOrEqual>`
* :doc:`GreaterThan </reference/constraints/GreaterThan>`
* :doc:`GreaterThanOrEqual </reference/constraints/GreaterThanOrEqual>`
* :doc:`Range </reference/constraints/Range>`
* :doc:`DivisibleBy </reference/constraints/DivisibleBy>`

日期约束
~~~~~~~~~~~~~~~~

* :doc:`Date </reference/constraints/Date>`
* :doc:`DateTime </reference/constraints/DateTime>`
* :doc:`Time </reference/constraints/Time>`

选择约束
~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Choice </reference/constraints/Choice>`
* :doc:`Language </reference/constraints/Language>`
* :doc:`Locale </reference/constraints/Locale>`
* :doc:`Country </reference/constraints/Country>`

文件约束
~~~~~~~~~~~~~~~~

* :doc:`File </reference/constraints/File>`
* :doc:`Image </reference/constraints/Image>`

财务和其他数字约束
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Bic </reference/constraints/Bic>`
* :doc:`CardScheme </reference/constraints/CardScheme>`
* :doc:`Currency </reference/constraints/Currency>`
* :doc:`Luhn </reference/constraints/Luhn>`
* :doc:`Iban </reference/constraints/Iban>`
* :doc:`Isbn </reference/constraints/Isbn>`
* :doc:`Issn </reference/constraints/Issn>`

其他约束
~~~~~~~~~~~~~~~~~

* :doc:`Callback </reference/constraints/Callback>`
* :doc:`Expression </reference/constraints/Expression>`
* :doc:`All </reference/constraints/All>`
* :doc:`Valid </reference/constraints/Valid>`
* :doc:`Collection </reference/constraints/Collection>`
* :doc:`Count </reference/constraints/Count>`
* :doc:`UniqueEntity </reference/constraints/UniqueEntity>`
* :doc:`Traverse </reference/constraints/Traverse>`
