* **行为守则**

  * :doc:`/contributing/code_of_conduct/code_of_conduct`
  * :doc:`/contributing/code_of_conduct/reporting_guidelines`
  * :doc:`/contributing/code_of_conduct/care_team`
  * :doc:`/contributing/code_of_conduct/concrete_example_document`

* **代码**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`拉取请求 </contributing/code/pull_requests>`
  * :doc:`审查问题和拉取请求 </contributing/community/reviews>`
  * :doc:`维护 </contributing/code/maintenance>`
  * :doc:`核心团队 </contributing/code/core_team>`
  * :doc:`安全 </contributing/code/security>`
  * :doc:`测试 </contributing/code/tests>`
  * :doc:`向后兼容性 </contributing/code/bc>`
  * :doc:`代码标准 </contributing/code/standards>`
  * :doc:`代码约定 </contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`许可 </contributing/code/license>`

* **文档**

  * :doc:`贡献文档 </contributing/documentation/overview>`
  * :doc:`文档格式 </contributing/documentation/format>`
  * :doc:`文档标准 </contributing/documentation/standards>`
  * :doc:`文档许可 </contributing/documentation/license>`

* **社区**

  * :doc:`发布流程 </contributing/community/releases>`
  * :doc:`尊重审查意见 </contributing/community/review-comments>`
  * :doc:`社区审查 </contributing/community/reviews>`

* **多样化**

  * :doc:`管理方法 </contributing/diversity/governance>`
